### ISSUE TITLE
Implement Dockerfile to build Alpine Linux

### ISSUE THREAD

**Issue by JanMate** [JanMate/happy_bank_core#16]

**Comment by Oleksandr6676** [comment]
Hi Jan! Do I need to specify some version of Alpine linux like in previous task? Also I would like to ask if I need to add some more instructions to this dockerfile (installing packages etc). Now it looks so empty

**Comment by JanMate** [comment]
> Hi Jan! Do I need to specify some version of Alpine linux like in previous task? Also I would like to ask if I need to add some more instructions to this dockerfile (installing packages etc). Now it looks so empty

Great question! I'll leave it to your imagination. If you think it's a good idea to add or copy there some files and set any configuration, let's do it. I'm absolutely OK with that. The important thing is build a running microservice with docker image.

On the other hand, if you are brave you can study how to build docker file for a python project to prepare a running environment for the core app. But at first, be focused on docker to switch to Kubernetes. Then we gonna implement the core app in python and connect it together.
