### ISSUE TITLE
Setup core app

### ISSUE THREAD

**Issue by JanMate** [JanMate/happy_bank_core#3]
1. Refactor repo structure:
   1. create new folder "core" in root of the repo and move there all current folders in the root folder.
   2. set the moved folders as python module (hint: https://naucse.python.cz/course/mi-pyt/intro/distribution/)
2. Update "workdir" config in Dockerfile to created "core" folder to fetch correctly python code into the docker image.
3. Prepare python venv to enable to run the python code for anybody who faces the repo.

Hint: https://github.com/MeStrak/dr-sven/blob/main/pyproject.toml

**Comment by Oleksandr6676** [comment]
Hi Jan, I have a questions regarding this one: 

> 1. Refactor repo structure:
>    1. create new folder "core" in root of the repo and move there all current folders in the root folder.
>    2. set the moved folders as python module (hint: https://naucse.python.cz/course/mi-pyt/intro/distribution/)

Do I need to create  just  one __init__.py file inside the "core" directory, or do I need  to create this file inside each directory, like here:  

core/
├─ cli/
│  ├─ cli.py
│  ├─ __init__.py
├─ data/
│  ├─ connector.py
│  ├─ memory.py
│  ├─ __init__.py
├─ logic/
│  ├─ transaction.py
│  ├─ __init__.py
├─ rest/
│  ├─ api.py
│  ├─ __init__.py

**Comment by Oleksandr6676** [comment]
It seems like inside each directory. Also we already have README and LICENSE files inside our root directory, do I need to create these in the core directory as well?

**Comment by Oleksandr6676** [comment]
> 3. Prepare python venv to anable to run the python code for anybody who faces the repo.

It should be done inside the dockerfile. right? Maybe I didn't unterstand it correctly

**Comment by JanMate** [comment]
> Hi Jan, I have a questions regarding this one:
> 
> > 1. Refactor repo structure:
> >    
> >    1. create new folder "core" in root of the repo and move there all current folders in the root folder.
> >    2. set the moved folders as python module (hint: https://naucse.python.cz/course/mi-pyt/intro/distribution/)
> 
> Do I need to create just one **init**.py file inside the "core" directory, or do I need to create this file inside each directory, like here:
> 
> core/ ├─ cli/ │ ├─ cli.py │ ├─ **init**.py ├─ data/ │ ├─ connector.py │ ├─ memory.py │ ├─ **init**.py ├─ logic/ │ ├─ transaction.py │ ├─ **init**.py ├─ rest/ │ ├─ api.py │ ├─ **init**.py

Every *.py file is module and every directory containing __init__.py file is module, too. So __init__.py file must be in core directory and its ancestor's directories.

**Comment by JanMate** [comment]
> It seems like inside each directory. Also we already have README and LICENSE files inside our root directory, do I need to create these in the core directory as well?

README and LICENSE is related to the repo so it belongs only to root directory. It's not related to python structure itself.

**Comment by JanMate** [comment]
> > 3. Prepare python venv to anable to run the python code for anybody who faces the repo.
> 
> It should be done inside the dockerfile. right? Maybe I didn't unterstand it correctly

It depends. On the one side, yes. But you need to have a list of dependencies that are needed to install before launching the app. 

I'll reveal that's related to python packages installed via pip.

**Comment by JanMate** [comment]
Could we add 'requirements.txt' file with python packages to make python setup env easier? It should be placed in root directory.

**Comment by Oleksandr6676** [comment]
> Could we add 'requirements.txt' file with python packages to make python setup env easier? It should be placed in root directory.
 
Sure, will do.  So when I run pip freeze command inside our happy_bank_core project I get the list of dependencies, for example: 

pywin32-ctypes==0.2.0
readme-renderer==30.0
requests==2.26.0
requests-toolbelt==0.9.1

etc.....

I need to add all of this to the requirements.txt file, right? And then use this requirements txt inside the dockerfile when building docker image like this
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

**Comment by JanMate** [comment]
> > Could we add 'requirements.txt' file with python packages to make python setup env easier? It should be placed in root directory.
> 
> Sure, will do. So when I run pip freeze command inside our happy_bank_core project I get the list of dependencies, for example:
> 
> pywin32-ctypes==0.2.0 readme-renderer==30.0 requests==2.26.0 requests-toolbelt==0.9.1
> 
> etc.....
> 
> I need to add all of this to the requirements.txt file, right? And then use this requirements txt inside the dockerfile when building docker image, something like this COPY requirements.txt requirements.txt RUN pip3 install -r requirements.txt

I got it absolutely right. 👍🏽
